apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-vlan-trunk 
spec:
  nodeSelector:
    #node-role.kubernetes.io/worker: '' 
    kubernetes.io/hostname: ocp4-lab-worker-3
  desiredState:
    interfaces:
    - name: bond1
      state: up
      type: bond
      link-aggregation:
        mode: 802.3ad
        port:
          - enp9s0
          - enp10s0
      ipv4:
        enabled: false
    - name: ovs-br1 
      description: |-
        A dedicated OVS bridge with bond1 as a port
        allowing all VLANs and untagged traffic
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: true
        port:
        - name: bond1 
    ovn:
      bridge-mappings:
      - localnet: vlan-1925 
        bridge: ovs-br1 
        state: present 
      - localnet: vlan-1926 
        bridge: ovs-br1 
        state: present 
    
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: VLAN 1925 connection for VMs
  name: vlan-1925
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "vlan-1925", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "default/vlan-1925",
      "vlanID": 1925,
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: VLAN 1926 connection for VMs
  name: vlan-1926
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "vlan-1926", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "default/vlan-1926",
      "vlanID": 1926,
      "ipam": {}
    }
