# The vlan does not have DHCP enabled, so the NAD is configured with an empty ipam section.
# Tested on Fedora Vm.
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cnv-linux-bridge-vlan-static
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "cnv-bridge",
      "bridge": "br1",
      "isGateway": true,
      "vlan": 1925,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.52.55/24",
            "gateway": "192.168.52.1"
          }
        ]
      }
    }