apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: example
spec:
  desiredState:
    interfaces:
      - name: bond1
        type: bond
        state: up
        link-aggregation:
          mode: '802.3ad'
          options:
            miimon: '140'
          port:
            - enp8s0
            - enp9s0
        ipv4:
          dhcp: false
          enabled: false
      - name: bond1.1925
        type: vlan
        state: up
        ipv4:
          dhcp: false
          enabled: false
        vlan:
          base-iface: bond1
          id: 1925
      - name: br1
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: true
          port:
            - name: bond1.1925
        ipv4:
          dhcp: false
          enabled: true
          address:
            - ip: 192.168.52.5
              prefix-length: 24
    routes:
      config:
        - destination: 192.168.52.0/24
          next-hop-address: 192.168.52.1
          next-hop-interface: br1
          table-id: 100
  nodeSelector:
    kubernetes.io/hostname: ocp4-lab-worker-5