apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond1-vlan1925-lab-worker-4
spec:
  desiredState:
    interfaces:
      - name: bond1
        type: bond
        state: up
        link-aggregation:
          mode: '802.3ad'
          options:
            miimon: '140'
          ports:
            - enp9s0
            - enp10s0
        ipv4:
          dhcp: false
          enabled: false
      - name: bond1.1925
        type: vlan
        state: up
        ipv4:
          dhcp: false
          enabled: false
        vlan:
          base-iface: bond1
          id: 1925
      - name: br-1
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: true
          port:
            - name: bond1.1925
        ipv4:
          dhcp: false
          enabled: false
    ovn:
      bridge-mappings:
        - localnet: localnet3
          bridge: br-1
          state: present
  nodeSelector:
    kubernetes.io/hostname: lab-worker-4
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: odf-public
  namespace: openshift-storage
spec:
  config: '{
  	"cniVersion": "0.3.1",
  	"type": "macvlan",
  	"master": "br-1",
  	"mode": "bridge",
  	"ipam": {
    	    "type": "whereabouts",
    	    "range": "192.168.52.0/24"
  	}
  }'
