# oc process -f templates/template-nncp-nic-br-vmdata.yaml \
#  -p NIC=ens224 \
#  -p NODE_SELECTOR_KEY=machine.openshift.io/cluster-api-machineset \
#  -p NODE_SELECTOR_VALUE=hub-tq2sk-cnv \
#  -o yaml | yq e '.items[0]' - > nncp-ens224-br-vmdata.yaml
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    description: Create bridge Linux br-vmdata with ens224 as a port
  labels:
    template: nncp-nic-vlan-br
  name: br-vmdata
spec:
  desiredState:
    interfaces:
      - name: ens224
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: br-vmdata
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens224
        ipv4:
          enabled: false
        ipv6:
          enabled: false