- op: replace
  path: /spec/source/repoURL
  value: 'https://github.com/tosin2013/demo-virt.git'
- op: replace
  path: /spec/source/targetRevision
  value: rhpds
- op: replace
  path: /spec/destination/server
  value: https://kubernetes.default.svc
- op: replace
  path: /metadata/name
  value: cluster-config-app-of-apps-demo1