---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

components:
  # this should have already been applied elsewhere
  #- ../components/networks/br-vmdata/ovs-bridge

  - ../../networking/components/multinetworkpolicy
  - ../../networking/components/vlan-1924/ovs-bridge
  - ../../networking/components/vlan-1926/ovs-bridge

  # be sure to update VM patches below to match vlan and namespace
  - ../../components/vms/rhel9

resources:
  - multinetworkpolicy.yaml

# the inline json patch can not learn of the random suffix
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudinitdisk-rhel-node
    files:
      - scripts/userData

  - name: admin-kubeconfig
    files:
      - secrets/kubeconfig

patches:
- target:
    group: kubevirt.io
    kind: VirtualMachine
    name: rhel-node-1
    version: v1
  patch: |-
    # pull cloud init script from secret
    - op: replace
      path: /spec/template/spec/volumes/1/cloudInitNoCloud
      value: {
        "secretRef": {
          "name": "cloudinitdisk-rhel-node"
        }
      }

    # add secret holding kubeconfig as volume
    - op: add
      path: /spec/template/spec/volumes/-
      value: {
        "name": "admin-kubeconfig",
        "secret": {
          "secretName": "admin-kubeconfig"
        }
      }
    # add secret volume as a disk
    - op: add
      path: /spec/template/spec/domain/devices/disks/-
      value: {
        "name": "admin-kubeconfig",
        "serial": "admin-kubeconfig",
        "disk": {
          "bus": "virtio"
        }
      }

    # convert default interface from masquerade to bridge 
    - op: replace
      path: /spec/template/spec/domain/devices/interfaces/0
      value: {
        "name": "nic-vlan-1924",
        "bridge": {},
        "model": "virtio"
      }

    # rehome default interface to network attachment definition
    # note namespace in net-attach-def multus reference if necessary
    - op: replace
      path: /spec/template/spec/networks/0
      value: {
        "name": "nic-vlan-1924",
        "multus": {
          "networkName": "default/vlan-1924"
        }
      }

    - op: add
      path: /spec/template/spec/domain/devices/interfaces/-
      value: {
        "name": "nic-vlan-1926",
        "bridge": {},
        "model": "virtio"
      }

    - op: add
      path: /spec/template/spec/networks/-
      value: {
        "name": "nic-vlan-1926",
        "multus": {
          "networkName": "default/vlan-1926"
        }
      }

    # start VM at creation
    - op: replace
      path: /spec/running
      value: true

    # live migrate VM if kicked off the node
    - op: add
      path: /spec/template/spec/evictionStrategy
      value: "LiveMigrate"
