---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - label
      - patch