---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: migration-network 
  namespace: openshift-cnv 
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "migration-bridge",
    "type": "macvlan",
    "master": "bond2.1927", 
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts", 
      "range": "192.168.56.0/24" 
    }
  }'