apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: netobserv
stringData:
  # oc extract secret/loki-bucket-claim -n netobserv --keys AWS_ACCESS_KEY_ID --to=-
  access_key_id: EXAMPLE
  # oc extract secret/loki-bucket-claim -n netobserv --keys AWS_SECRET_ACCESS_KEY --to=-
  access_key_secret: EXAMPLE
  endpoint: https://s3.openshift-storage.svc
  bucketnames: netobserv-loki-bucket
