---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nad-vlan-cnv-bridge
  annotations:
    description: >-
      A NetworkAttachmentDefinition resource to enable access to a VLAN via a Linux bridge interface.

      Results can be used to multi-home pods using Multus.

    iconClass: icon-load-balancer
    openshift.io/provider-display-name: GUIFreeLife
    openshift.io/documentation-url: https://github.com/dlbewley/demo-virt
    openshift.io/support-url: https://github.com/dlbewley/demo-virt/issues
    tags: "networking,nmstate"

objects:
  - apiVersion: k8s.cni.cncf.io/v1
    kind: NetworkAttachmentDefinition
    metadata:
      annotations:
        description: ${DESCRIPTION}
        k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-${VLAN}
      labels:
        template: nad-vlan-vnc-bridge
      name: vlan-${VLAN}
      namespace: ${NAMESPACE}
    spec:
      config: |
        {
          "name": "vlan-${VLAN}",
          "bridge": "br-${VLAN}",
          "cniVersion": "0.3.1",
          "type": "cnv-bridge",
          "macspoofchk": true
        }

parameters:
  - description: VLAN ID
    name: VLAN
    required: true
  - description: Namespace
    name: NAMESPACE
    value: default
  - description: Net-attach-def description
    name: DESCRIPTION
    value: Attachment to br-${VLAN}
