# Example looping of template using zsh syntax
# unset vlans
# declare -A vlans
# NIC=ens224
# vlans[1924]="Lab"
# vlans[1925]="Disco"
# vlans[1926]="Trans Proxy"
# vlans[1927]="Metal"
# vlans[1928]="Provisioning"
# 
# for VLAN in ${(k)vlans}; do
#   oc process \
#     -p VLAN="$V" \
#     -p NIC="$NIC" \
#     -p NODE_SELECTOR_KEY=machine.openshift.io/cluster-api-machineset \
#     -p NODE_SELECTOR_VALUE=hub-l7c56-cnv \
#     -p DESCRIPTION="Add ${vlans[$VLAN]} VLAN ${VLAN} and Bridge br-${VLAN} on ${NIC}" \
#     -f templates/template-nncp-nic-vlan-br.yaml \
#     -o yaml \
#     | yq e '.items[0]' > "networking/nncp/nncp-$NIC-br-vlan-$VLAN.yaml"
#   echo $k
# done
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nncp-nic-vlan-br
  annotations:
    description: >-
      A NodeNetworkConfigurationPolicy to add a VLAN interface to a NIC and attach a bridge for the VLAN. The bridge can be targeted by namespaced NetworkAttachmentDefinitions.

      |<802.1q>|
      |<-- NNCP ----------------->|<-- NAD -->|
      [host-NIC]--+-[vlan1]-[BR1]--[guest-nic]
                   \[vlan2]-[BR2]--[guest-nic]

      See https://access.redhat.com/solutions/6972064

    iconClass: icon-load-balancer
    openshift.io/provider-display-name: GUIFreeLife
    openshift.io/documentation-url: https://github.com/dlbewley/demo-virt
    openshift.io/support-url: https://github.com/dlbewley/demo-virt/issues
    tags: "networking,nmstate"

objects:
  - apiVersion: nmstate.io/v1
    kind: NodeNetworkConfigurationPolicy
    metadata:
      name: ${NIC}-v${VLAN}
      annotations:
        description: ${DESCRIPTION}
      labels:
        template: nncp-nic-vlan-br
    spec:
      nodeSelector:
        ${NODE_SELECTOR_KEY}: ${NODE_SELECTOR_VALUE}
      desiredState:
        interfaces:
          - name: ${NIC}
            type: ${NIC_TYPE}
            state: up
            ipv4:
              enabled: false
            ipv6:
              enabled: false

          - name: ${NIC}.${VLAN}
            type: vlan
            state: up
            vlan:
              base-iface: ${NIC}
              id: ${VLAN}
            ipv4:
              enabled: false
            ipv6:
              enabled: false

          - name: br-${VLAN}
            type: linux-bridge
            state: up
            bridge:
              options:
                stp:
                  enabled: false
              port:
                - name: ${NIC}.${VLAN}
                  vlan: {}
            ipv4:
              enabled: false
            ipv6:
              enabled: false

parameters:
  - description: Physical NIC or Bond to add VLAN interface and bridge to
    name: NIC
    value: ens224
    required: true
  - description: NIC Interface type. eg ethernet, bond
    name: NIC_TYPE
    value: ethernet
    required: false
  - description: VLAN ID
    name: VLAN
    required: true
  - description: Node Selector Key
    name: NODE_SELECTOR_KEY
    value: machine.openshift.io/cluster-api-machineset
  - description: Node Selector Value
    name: NODE_SELECTOR_VALUE
    value: ''
    required: false
  - description: Policy description
    name: DESCRIPTION
    # modify these by hand in the NNCP resource
    value: Add VLAN ${VLAN} and Bridge br-${VLAN} on ${NIC}
