apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond1-vlan1925-odf
spec:
  desiredState:
    interfaces:
      - name: bond1
        type: bond
        state: absent
        link-aggregation:
          mode: '802.3ad'
          options:
            miimon: '140'
          ports:
            - enp9s0
            - enp10s0
        ipv4:
          dhcp: false
          enabled: false
      - name: bond1.1925
        type: vlan
        state: absent
        ipv4:
          dhcp: false
          enabled: false
        vlan:
          base-iface: bond1
          id: 1925
      - name: br-1925
        type: linux-bridge
        state: absent
        bridge:
          options:
            stp:
              enabled: true
          port:
            - name: bond1.1925
        ipv4:
          dhcp: false
          enabled: false
      - name: macvlan1
        type: mac-vlan
        state: absent
        macvlan:
          mode: bridge
          base-iface: bond1.1925
        ipv4:
          dhcp: false
          enabled: true
    ovn:
      bridge-mappings:
        - localnet: localnet3
          bridge: br-1925
          state: absent
  nodeSelector:
    node-role.kubernetes.io/infra: '' 